feat(tablepanel): add TablePanel component
Conflux-Chain/sirius pull request #13
Opened 2020-09-23 02:28 UTC by chain-txz

1. add TablePanel component
2. add blocks&transactions page with TablePanel

2020-09-23 05:45 UTC, angelia-yuqi-personal requested changes

2020-09-23 05:45 UTC, angelia-yuqi-personal commented on src/styles/global-styles.ts
> +    html {
missed body

2020-09-24 03:49 UTC, yqrashawn commented
no effect when change the page size query, eg `blocks-and-transactions/blocks?page=1&pageSize=20`

2020-10-06 10:09 UTC, angelia-yuqi-personal approved these changes

2020-10-08 04:54 UTC, angelia-yuqi-personal approved these changes

2020-10-08 06:07 UTC, merged