refactor: add useTabTableData and useTableData
Conflux-Chain/sirius pull request #16
Opened 2020-09-30 11:23 UTC by yqrashawn

2020-10-02 14:30 UTC, angelia-yuqi-personal requested changes

2020-10-02 14:30 UTC, angelia-yuqi-personal commented on src/app/containers/BlocksAndTransactions/index.tsx
> +        key="transactions"
transactions => currentTabValue

2020-10-03 03:02 UTC, yqrashawn commented on src/app/containers/BlocksAndTransactions/index.tsx
> +        key="transactions"
done

2020-10-03 03:03 UTC, angelia-yuqi-personal approved these changes

2020-10-03 03:08 UTC, merged