feat(style): update styled component
Conflux-Chain/sirius pull request #43
Opened 2020-10-14 08:19 UTC by chain-txz

2020-10-14 10:45 UTC, angelia-yuqi-personal requested changes

2020-10-14 10:52 UTC, chain-txz commented on src/app/components/Card/__tests__/index.test.tsx
> +describe('<Tooltip />', () => {
Fixed.

2020-10-14 10:52 UTC, chain-txz commented on src/app/components/Card/__tests__/index.test.tsx
> +  it('should match the snapshot', () => {
Fixed.

2020-10-14 11:27 UTC, angelia-yuqi-personal requested changes

2020-10-14 11:27 UTC, angelia-yuqi-personal commented on src/app/components/Text/index.tsx
> +  maxWidth?: string; // todo, camel-case naming will cause warning in console, keep now and will resolve later
remove todo

2020-10-14 11:33 UTC, chain-txz commented on src/app/components/Text/index.tsx
> +  maxWidth?: string; // todo, camel-case naming will cause warning in console, keep now and will resolve later
done

2020-10-14 11:35 UTC, angelia-yuqi-personal requested changes

2020-10-14 11:35 UTC, angelia-yuqi-personal commented on src/app/containers/BlocksAndTransactions/index.tsx
> +  <Text span maxWidth={'5.7143rem'} hoverValue={value}>
这里为啥要用大括号括起来，直接""不行吗？

2020-10-15 02:40 UTC, angelia-yuqi-personal approved these changes

2020-10-15 02:44 UTC, merged