feat：add chart page
Conflux-Chain/sirius pull request #46
Opened 2020-10-14 10:46 UTC by GuichiZhao

2020-10-14 10:59 UTC, angelia-yuqi-personal requested changes

2020-10-14 10:59 UTC, angelia-yuqi-personal commented on src/app/components/Chart/SmallChart.jsx
> +import React from 'react';
这个smallChart有啥用

2020-10-14 10:59 UTC, angelia-yuqi-personal commented on .vscode/settings.json
> +  "[javascriptreact]": {
为啥要添加这个

2020-10-14 10:59 UTC, angelia-yuqi-personal commented on src/app/containers/Chart/index.jsx
> +function App() {
这里不要用App这样的名字，应该是Chart

2020-10-14 10:59 UTC, angelia-yuqi-personal commented on src/app/containers/Chart/index.jsx
> +import Chart from '../../components/Chart/Chart';
这里可以用Chart as ChartComponent

2020-10-14 10:59 UTC, angelia-yuqi-personal commented on src/app/components/Chart/Chart.jsx
> +import React, { useState, useRef, useEffect } from 'react';
这个文件名应该是index

2020-10-14 10:59 UTC, angelia-yuqi-personal commented on src/app/components/Chart/Chart.jsx
> +import React, { useState, useRef, useEffect } from 'react';
应该添加Loadabele.ts文件，请参考其他组件

2020-10-14 10:59 UTC, angelia-yuqi-personal commented on src/app/containers/Chart/index.jsx
> +import Chart from '../../components/Chart/Chart';
这里应该用懒加载

2020-10-15 02:55 UTC, angelia-yuqi-personal requested changes

2020-10-15 02:55 UTC, angelia-yuqi-personal commented on src/app/index.tsx
> +import Chart from './containers/Chart/index';
这里应该用懒加载

2020-10-15 09:14 UTC, yqrashawn requested changes

2020-10-15 09:14 UTC, yqrashawn commented on .vscode/settings.json
> +    "editor.defaultFormatter": "vscode.typescript-language-features"
why change the formatter here?

2020-10-15 12:43 UTC, yqrashawn approved these changes

2020-10-16 06:10 UTC, angelia-yuqi-personal approved these changes

2020-10-16 06:10 UTC, merged